version: "2"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/meme
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    